# Generated by Django 5.2 on 2025-12-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_actors_movie_director_movie_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='overview_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
