# Generated by Django 5.2 on 2025-12-24 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0003_movie_overview_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_mood', models.CharField(max_length=50)),
                ('score_details', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mood_result', to='movies.movie')),
            ],
        ),
    ]
